import me.champeau.jmh.JMHTask

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */
plugins {
    java
    id("me.champeau.jmh") version "0.7.1"

}

group = "com.priyakdey"
version = "0.0.1-SNAPSHOT"

java {
    sourceCompatibility = JavaVersion.VERSION_20
    targetCompatibility = JavaVersion.VERSION_20
}

repositories {
    mavenCentral()
}

val junitVersion: String by project

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testImplementation("org.junit.jupiter:junit-jupiter-params:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.withType<JMHTask> {
    jvmArgs = listOf("-XX:+PreserveFramePointer", "-XX:+UnlockDiagnosticVMOptions", "-XX:+DebugNonSafepoints")
    humanOutputFile = project.file("/human.txt")            // human-readable output file
    resultsFile = project.file("benchmark.txt")             // results file
    threads = Runtime.getRuntime().availableProcessors()
}
